### ISSUE TITLE
Cannot find module '#open-fetch-schemas/..."

### ISSUE THREAD

**Issue by schillerenrico** [enkot/nuxt-open-fetch#71]
### Environment

Nuxt 4

### Reproduction

Start a project with nuxt-open-fetch 0.9.1 and start it with npm run dev
npm update to get to version 0.9.2
and start again

### Describe the bug

inside .nuxt\open-fetch.ts
the import type { paths as ... throws the following error inside the IDE
Cannot find module '#open-fetch-schemas/***' or its corresponding type declarations.

but it works in 0.9.1 not in 0.9.2

### Additional context

you need to run "npm run dev" after changing from 0.9.1 to 0.9.2 to see the error inside .nuxt\open-fetch.ts

**Comment by schillerenrico** [comment]
For now I am using

"devDependencies": { "nuxt-open-fetch": "0.9.1",...

not 0.9.2 to have a working project in my IDE. Cause otherwise all the endpoints have an any type

**Comment by TheDutchCoder** [comment]
I run into this issue as well.
It's odd, since the generated `./nuxt/tsconfig.json` does seem to have the right entries:
```json
      "#open-fetch": [
        "./open-fetch"
      ],
      "#open-fetch-schemas/*": [
        "./types/open-fetch/schemas/*"
      ],
```

The IDE (Cursor) picks it up fine, but a nuxt typecheck fails on it 🤔

**Comment by Norbiros** [comment]
On which version? 0.13 or something below?

**Comment by TheDutchCoder** [comment]
Okay I think the issue is that we tried putting the openapi folder in `/app`, and that breaks TS.
If you keep it in the root then it seems to work.
